node ('node2') {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/jglick/simple-maven-project-with-tests.git'
      
   }
   stage('Build') {
      
            sh 'ls'
            
    
        
   }
   stage('Results') {
      sh 'echo success'
   }
}